### ISSUE TITLE
Thumbnail issues - probably not storage related

### ISSUE THREAD

**Issue by ddcornwall** [usnationalarchives/Catalog-API#10] opened 2018-04-09 14:08 UTC
I found two records where the API thumbnail for the first item is broken, but I don't think it's the storage issue you know about. In both of the records below, only object[0]'s thumbnail is broken. However while the other objects have  working thumbnails, those thumbnails seem to be one item behind the thumbails in the catalog. 

Comparing the JSON output to what's in the catalog it seems like the first thumbnail in the catalog corresponds to object[1]'s thumbnail in the API/JSON output:

Title: June 22, 1939 Loose Dogs
Parent Series: Circulars Relating to Reindeer Herding in Alaska
Catalog - https://catalog.archives.gov/id/46750793
JSON - https://catalog.archives.gov/api/v1/?naIds=46750793
NaID = 46750793

Title: Circ. to Owners - 6/26/37 Re: Killing Dogs on Ranges
Parent Series: Circulars Relating to Reindeer Herding in Alaska
Catalog - https://catalog.archives.gov/id/46750773
JSON - https://catalog.archives.gov/api/v1/?naIds=46750773
NaID = 46750773

In most records, it would be object[0]'s thumbnail that would correspond to the first thumbnail in the catalog.

Thanks for looking into this.

**Comment by DominicBM** [comment] 2018-04-10 16:14
Hi @ddcornwall, thanks again for letting us know about issues! I checked with our catalog staff, and in this case it looks like the issue is not API-related, but a data entry issue. That series does not actually have any PDFs, but a PDF URL was entered. The system also failed to render thumbnails from the bad media file URL, and both the PDF and its thumbnail URLs are broken as a result. I think the solution will simply be to delete the missing PDF objects from the catalog. This is not any loss of data, since generally PDFs in records like these are optional duplicates of the JPG page images. So, fix is in progress, but note that data changes in our description system can take a couple of weeks to go live in the catalog, as data is ingested periodically rather than in real-time.

**Closed by DominicBM** 2018-04-10 16:14 UTC
